stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  LANG: en_US.UTF-8

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  services:
    - selenium/standalone-chrome:latest
  before_script:
    - apt-get update && apt-get install -y wget unzip curl gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - chmod +x ./chromedriver.exe

  script:
    - mvn clean test -DsuiteXmlFile=testngsuite.xml
    - echo "Conteúdo do diretório src/test/java/documents:"
    - ls -la src/test/java/documents/
    - ls -la src/test/java/documents/AddProductDocuments || echo "AddProductDocuments não existe"
    - ls -la src/test/java/documents/CheckoutDocuments || echo "CheckoutDocuments não existe"
    - ls -la src/test/java/documents/EditAccountDocuments || echo "EditAccountDocuments não existe"
    - ls -la src/test/java/documents/EditPassDocuments || echo "EditPassDocuments não existe"
    - ls -la src/test/java/documents/ForgottenPassDocuments || echo "ForgottenPassDocuments não existe"
    - ls -la src/test/java/documents/LoginTestDocuments || echo "LoginTestDocuments não existe"
    - ls -la src/test/java/documents/LogoutTestDocuments || echo "LogoutTestDocuments não existe"
    - ls -la src/test/java/documents/OrderHistoryDocuments || echo "OrderHistoryDocuments não existe"
    - ls -la src/test/java/documents/RegisterTestDocuments || echo "RegisterTestDocuments não existe"
    - ls -la src/test/java/documents/SearchProductDocuments || echo "SearchProductDocuments não existe"
    - ls -la src/test/java/documents/WishTestDocuments || echo "WishTestDocuments não existe"

  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - src/test/java/documents/AddProductDocuments/
      - src/test/java/documents/CheckoutDocuments/
      - src/test/java/documents/EditAccountDocuments/
      - src/test/java/documents/EditPassDocuments/
      - src/test/java/documents/ForgottenPassDocuments/
      - src/test/java/documents/LoginTestDocuments/
      - src/test/java/documents/LogoutTestDocuments/
      - src/test/java/documents/OrderHistoryDocuments/
      - src/test/java/documents/RegisterTestDocuments/
      - src/test/java/documents/SearchProductDocuments/
      - src/test/java/documents/WishTestDocuments/
    expire_in: 1 week
