stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  LANG: en_US.UTF-8

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium

  script:
    - mvn clean test -DsuiteXmlFile=testngsuite.xml
    - echo "Conteúdo do diretório documents:"
    - ls -la documents/
    - ls -la documents/AddProductDocuments || echo "AddProductDocuments não existe"
    - ls -la documents/CheckoutDocuments || echo "CheckoutDocuments não existe"
    - ls -la documents/EditAccountDocuments || echo "EditAccountDocuments não existe"
    - ls -la documents/EditPassDocuments || echo "EditPassDocuments não existe"
    - ls -la documents/ForgottenPassDocuments || echo "ForgottenPassDocuments não existe"
    - ls -la documents/LoginTestDocuments || echo "LoginTestDocuments não existe"
    - ls -la documents/LogoutTestDocuments || echo "LogoutTestDocuments não existe"
    - ls -la documents/OrderHistoryDocuments || echo "OrderHistoryDocuments não existe"
    - ls -la documents/RegisterTestDocuments || echo "RegisterTestDocuments não existe"
    - ls -la documents/SearchProductDocuments || echo "SearchProductDocuments não existe"
    - ls -la documents/WishTestDocuments || echo "WishTestDocuments não existe"

  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - documents/
    expire_in: 1 week
