stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  LANG: en_US.UTF-8

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  services:
    - selenium/standalone-chrome:latest
  before_script:
    - apt-get update && apt-get install -y wget unzip curl gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - chmod +x ./chromedriver.exe

  script:
    - mvn clean test -DsuiteXmlFile=testngsuite.xml

  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - AddProductDocuments/
      - CheckoutDocuments/
      - EditAccountDocuments/
      - EditPassDocuments/
      - ForgottenPassDocuments/
      - LoginTestDocuments/
      - LogoutTestDocuments/
      - OrderHistoryDocuments/
      - RegisterTestDocuments/
      - SearchProductDocuments/
      - WishTestDocuments/
    expire_in: 1 week
